#ifndef ACTOR_COMPONENT_DEFINITIONS_H
#define ACTOR_COMPONENT_DEFINITIONS_H

// default actor types
enum DEFAULT_ACTOR_TYPES {
    ACTOR_EMPTY,
    ACTOR_STATIC,
    ACTOR_ENEMY,
    ACTOR_PLAYER,
};

#endif